#pragma once

//#define PIMORONI_PICO_PLUS2_PSRAM_CS_PIN 47
//#define RP2350_PSRAM_CS PIMORONI_PICO_PLUS2_PSRAM_CS_PIN
#ifdef PIMORONI_PICO_PLUS2_RP2350
#define RP2350_PSRAM_CS 47
#define PSRAM_HEAP 1
#endif