#
# makefile for Packet Drivers for Turbo Make.  MS-Make loses.
#

# if you use Borland products
ASM	=	tasm
LINK	=	tlink

# If you use Microsoft products (some lossage will ensue).  Great
# lossage will ensue if you use masm 4.0, but most things will
# assemble.  For those that do not, simply create the .obj file by
# hand, then create the .com file.  That will enable make to skip
# over them.  Please send the editor email
# <nelson@crynwr.com>, or a FAX <315-268-9201> if Microsoft
# support is useful to you.
#ASM	=	masm
#LINK	=	link

# Some of the assembly language source files are part of a
# general-purpose library.  Point $(INC) to the location of the library.
INC	=	\asm\include

# These are split into ASM and C files because you may not have Turbo C.
# If you don't, then remove the "c" dependency from the following:
all:	drivers utilities c

# Begin drivers
3Com: 3c501.com 3c503.com 3c505.com 3c507.com 3c523.com 3c509.com
ADI: aquila.com
Allied-Telesis: at1500.com at1700.com
ARCNET: arcnet.com arcether.com
AT&T-NCR: at&t.com at&t_lp.com ncret105.com
BICC: isolan.com isolink.com
Cabletron: ctrondni.com
D-Link: de600.com
DEC: depca.com vaxmate.com
David-Systems: davidsys.com
Eagle-Technologies: ne1000.com ne2000.com ne2.com ne2100.com
Fujitsu: dk86960.com dk86965.com
HP: hppclan.com hppclanp.com
ICL-Etherteam: ethiie.com
Intel-EtherExpress: exp16.com #enic960.com
Kodiak-Technologies: kodiak8.com kodiak16.com kodiakk.com
Microdyne: exos205.com
Multitech: en301.com
Mylex: mylex.com
PLIP: plip.com
Racal-Interlan:	ni5010.com ni5210.com ni9210.com ni6510.com es3210.com
SLIP: slip8250.com ethersl.com
SMC: smc_wd.com wd8003e.com #pkt8000.com pkt8232.com pkt8016.com
Telesystems-SLW: ar450.com
Thomas-Conrad: tcenet.com
Tiara: tiara.com
Ungarmann-Bass: ubnicpc.com ubnicps2.com
Zenith-Data-Systems: znote.com
misc: nti16.com express.com pi.com skeleton.com
shims: 	ibmtoken.com localtlk.com nb.com ipxpkt.com
# End drivers

# This is automatically created.  Do not edit it!
drivers: 3Com ADI Allied-Telesis ARCNET AT&T-NCR BICC \
 Cabletron D-Link DEC David-Systems Eagle-Technologies \
 Fujitsu HP ICL-Etherteam Intel-EtherExpress Kodiak-Technologies \
 Microdyne Multitech Mylex PLIP Racal-Interlan SLIP \
 SMC Telesystems-SLW Thomas-Conrad Tiara Ungarmann-Bass \
 Zenith-Data-Systems misc shims


utilities: \
	pktchk.com trace.com termin.com pktmode.com pktaddr.com pktall.com \
	pktmulti.com pktsend.com pktstat.com pktwatch.com winpkt.com \
	pkttraf.com

c:	dump.exe ipxstat.exe seepkt.exe

.asm.obj:
	$(ASM) /I$(INC) $*;

FLAGS = -ml -v -w -M

seepkt.exe: seepkt.obj pktdrvr.obj
	bccx $(FLAGS) seepkt.obj pktdrvr.obj

pktdrvr.obj: pktdrvr.c pktdrvr.h
	bccx -c $(FLAGS) pktdrvr.c

seepkt.obj: seepkt.c pktdrvr.h
	bccx -c $(FLAGS) seepkt.c

dump.obj: dump.c
	bccx -c dump.c

dump.exe: dump.obj
	bccx -edump dump.obj

ipxstat.obj: ipxstat.c
	bccx -mc -c ipxstat.c

ipxstat.exe: ipxstat.obj
	bccx -mc -eipxstat ipxstat.obj

termin.com: termin.obj
	$(LINK) termin;
	exe2com termin
	del termin.exe

trace.com: trace.obj
	$(LINK) trace;
	exe2com trace
	del trace.exe

pktmode.com: pktmode.obj defs.asm
	$(LINK) pktmode;
	exe2com pktmode
	del pktmode.exe

pktaddr.com: pktaddr.obj defs.asm
	$(LINK) pktaddr;
	exe2com pktaddr
	del pktaddr.exe

pktall.com: pktall.obj defs.asm
	$(LINK) pktall;
	exe2com pktall
	del pktall.exe

pkttraf.com: pkttraf.obj defs.asm
	$(LINK) pkttraf;
	exe2com pkttraf
	del pkttraf.exe

pktmulti.com: pktmulti.obj defs.asm
	$(LINK) pktmulti;
	exe2com pktmulti
	del pktmulti.exe

pktchk.com: pktchk.obj defs.asm
	$(LINK) pktchk;
	exe2com pktchk
	del pktchk.exe

pktsend.com: pktsend.obj defs.asm
	$(LINK) pktsend;
	exe2com pktsend
	del pktsend.exe

pktstat.com: pktstat.obj defs.asm
	$(LINK) pktstat;
	exe2com pktstat
	del pktstat.exe

pktwatch.com: pktwatch.obj defs.asm
	$(LINK) pktwatch;
	exe2com pktwatch
	del pktwatch.exe

winpkt.com: winpkt.obj defs.asm
	$(LINK) winpkt;
	exe2com winpkt
	del winpkt.exe

pktrmt.com: pktrmt.obj defs.asm
	$(LINK) pktrmt;
	exe2com pktrmt
	del pktrmt.exe

head.obj: head.asm defs.asm

at1500.obj: at1500.asm lance.asm

at1500.com: head.obj at1500.obj tail.obj
	$(LINK) head at1500 tail,at1500/m;
	exe2com at1500
	del at1500.exe

at1700.obj: at1700.asm ecoupler.asm

at1700.com: head.obj at1700.obj tail.obj
	$(LINK) head at1700 tail,at1700/m;
	exe2com at1700
	del at1700.exe

3c501.com: head.obj 3c501.obj tail.obj
	$(LINK) head 3c501 tail,3c501/m;
	exe2com 3c501
	del 3c501.exe

3c503.obj: 3c503.asm 8390.asm

3c503.com: head.obj 3c503.obj tail.obj
	$(LINK) head 3c503 tail,3c503/m;
	exe2com 3c503
	del 3c503.exe

3c505.com: head.obj 3c505.obj tail.obj
	$(LINK) head 3c505 tail,3c505/m;
	exe2com 3c505
	del 3c505.exe

3c507.obj: 3c507.asm 82586.asm

3c507.com: head.obj 3c507.obj tail.obj
	$(LINK) head 3c507 tail,3c507/m;
	exe2com 3c507
	del 3c507.exe

3c509.com: head.obj 3c509.obj tail.obj
	$(LINK) head 3c509 tail,3c509/m;
	exe2com 3c509
	del 3c509.exe

3c523.obj: 3c523.asm 82586.asm

3c523.com: head.obj 3c523.obj tail.obj
	$(LINK) head 3c523 tail,3c523/m;
	exe2com 3c523
	del 3c523.exe

at&t.obj: at&t.asm 82586.asm

at&t.com: head.obj at&t.obj tail.obj
	$(LINK) head at&t tail,at&t/m;
	exe2com at&t
	del at&t.exe

at&t_lp.obj: at&t_lp.asm t7231.asm

at&t_lp.com: head.obj at&t_lp.obj tail.obj
	$(LINK) head at&t_lp tail,at&t_lp/m;
	exe2com at&t_lp
	del at&t_lp.exe

localtlk.com: head.obj localtlk.obj tail.obj
	$(LINK) head localtlk tail,localtlk/m;
	exe2com localtlk
	del localtlk.exe

ubnicpc.com: head.obj ubnicpc.obj tail.obj
	$(LINK) head ubnicpc tail,ubnicpc/m;
	exe2com ubnicpc
	del ubnicpc.exe

ubnicps2.obj: ubnicps2.asm 82586.asm

ubnicps2.com: head.obj ubnicps2.obj tail.obj
	$(LINK) head ubnicps2 tail,ubnicps2/m;
	exe2com ubnicps2
	del ubnicps2.exe

ncret105.obj: ncret105.asm 82586.asm

ncret105.com: head.obj ncret105.obj tail.obj
	$(LINK) head ncret105 tail,ncret105/m;
	exe2com ncret105
	del ncret105.exe

nti16.com: head.obj nti16.obj tail.obj
	$(LINK) head nti16 tail,nti16/m;
	exe2com nti16
	del nti16.exe

ctrondni.obj: ctrondni.asm 8390.asm

ctrondni.com: head.obj ctrondni.obj tail.obj
	$(LINK) head ctrondni tail,ctrondni/m;
	exe2com ctrondni
	del ctrondni.exe

hppclan.obj: hppclan.asm 8390.asm

hppclan.com: head.obj hppclan.obj tail.obj
	$(LINK) head hppclan tail,hppclan/m;
	exe2com hppclan
	del hppclan.exe

hppclanp.obj: hppclanp.asm 8390.asm

hppclanp.com: head.obj hppclanp.obj tail.obj
	$(LINK) head hppclanp tail,hppclanp/m;
	exe2com hppclanp
	del hppclanp.exe

ni5010.com: head.obj ni5010.obj tail.obj
	$(LINK) head ni5010 tail,ni5010/m;
	exe2com ni5010
	del ni5010.exe

ni5210.obj: ni5210.asm 82586.asm

ni5210.com: head.obj ni5210.obj tail.obj
	$(LINK) head ni5210 tail,ni5210/m;
	exe2com ni5210
	del ni5210.exe

ni9210.obj: ni9210.asm 82586.asm

ni9210.com: head.obj ni9210.obj tail.obj
	$(LINK) head ni9210 tail,ni9210/m;
	exe2com ni9210
	del ni9210.exe

ni6510.obj: ni6510.asm lance.asm

ni6510.com: head.obj ni6510.obj tail.obj
	$(LINK) head ni6510 tail,ni6510/m;
	exe2com ni6510
	del ni6510.exe

es3210.obj: es3210.asm 8390.asm

es3210.com: head.obj es3210.obj tail.obj
	$(LINK) head es3210 tail,es3210/m;
	exe2com es3210
	del es3210.exe

depca.com: head.obj depca.obj tail.obj
	$(LINK) head depca tail,depca/m;
	exe2com depca
	del depca.exe

vaxmate.com: head.obj vaxmate.obj tail.obj
	$(LINK) head vaxmate tail,vaxmate/m;
	exe2com vaxmate
	del vaxmate.exe

express.com: head.obj express.obj tail.obj
	$(LINK) head express tail,express/m;
	exe2com express
	del express.exe

ar450.com: head.obj ar450.obj tail.obj
	$(LINK) head ar450 tail,ar450/m;
	exe2com ar450
	del ar450.exe

en301.com: head.obj en301.obj tail.obj
	$(LINK) head en301 tail,en301/m;
	exe2com en301
	del en301.exe

kodiak8.obj: kodiak8.asm kodiak.asm

kodiak8.com: head.obj kodiak8.obj tail.obj
	$(LINK) head kodiak8 tail,kodiak8/m;
	exe2com kodiak8
	del kodiak8.exe

kodiak16.obj: kodiak16.asm kodiak.asm

kodiak16.com: head.obj kodiak16.obj tail.obj
	$(LINK) head kodiak16 tail,kodiak16/m;
	exe2com kodiak16
	del kodiak16.exe

kodiakk.obj: kodiakk.asm kodiak.asm

kodiakk.com: head.obj kodiakk.obj tail.obj
	$(LINK) head kodiakk tail,kodiakk/m;
	exe2com kodiakk
	del kodiakk.exe

znote.com: head.obj znote.obj tail.obj
	$(LINK) head znote tail,znote/m;
	exe2com znote
	del znote.exe

isolan.com: head.obj isolan.obj tail.obj
	$(LINK) head isolan tail,isolan/m;
	exe2com isolan
	del isolan.exe

isolink.com: head.obj isolink.obj tail.obj
	$(LINK) head isolink tail,isolink/m;
	exe2com isolink
	del isolink.exe

exp16.obj: exp16.asm exp16mca.asm exp16.inc

exp16.com: head.obj exp16.obj tail.obj
	$(LINK) head exp16 tail,exp16/m;
	exe2com exp16
	del exp16.exe

enic960.com: head.obj enic960.obj tail.obj
	$(LINK) head enic960 tail,enic960/m;
	exe2com enic960
	del enic960.exe

slip8250.obj: slip8250.asm slipmerg.asm

slip8250.com: head.obj slip8250.obj tail.obj 8250defs.asm
	$(LINK) head slip8250 tail,slip8250/m;
	exe2com slip8250
	del slip8250.exe

ethersl.obj: ethersl.asm slipmerg.asm

ethersl.com: head.obj ethersl.obj tail.obj 8250defs.asm
	$(LINK) head ethersl tail,ethersl/m;
	exe2com ethersl
	del ethersl.exe

plip.com: head.obj plip.obj tail.obj
	$(LINK) head plip tail,plip/m;
	exe2com plip
	del plip.exe

smc_wd.obj: smc_wd.asm 8390.asm

smc_wd.com: head.obj smc_wd.obj tail.obj
	$(LINK) head smc_wd tail,smc_wd/m;
	exe2com smc_wd
	del smc_wd.exe

wd8003e.com: wd8003e.obj
	$(LINK) wd8003e,wd8003e/m;
	exe2com wd8003e
	del wd8003e.exe

pkt8000.obj: pkt8000.asm umac.asm
	$(ASM) /I$(INC) /Iultra\lminc pkt8000, pkt8000;

pkt8000.com: head.obj pkt8000.obj tail.obj
	$(LINK) head pkt8000 tail,pkt8000/m;
	exe2com pkt8000
	del pkt8000.exe

pkt8232.obj: pkt8232.asm umac.asm
	$(ASM) /I$(INC) /Ismceisa /Iultra\lminc pkt8232, pkt8232;

pkt8232.com: head.obj pkt8232.obj tail.obj
	$(LINK) head pkt8232 tail,pkt8232/m;
	exe2com pkt8232
	del pkt8232.exe

pkt8016.obj: pkt8016.asm umac.asm
	$(ASM) /I$(INC) /Ismcpcmcia pkt8016, pkt8016;

pkt8016.com: head.obj pkt8016.obj tail.obj
	$(LINK) head pkt8016 tail,pkt8016/m;
	exe2com pkt8016
	del pkt8016.exe

ibmtoken.com: head.obj ibmtoken.obj tail.obj
	$(LINK) head ibmtoken tail,ibmtoken/m;
	exe2com ibmtoken
	del ibmtoken.exe

ne1000.obj: ne1000.asm 8390.asm

ne1000.com: head.obj ne1000.obj tail.obj
	$(LINK) head ne1000 tail,ne1000/m;
	exe2com ne1000
	del ne1000.exe

ne2000.obj: ne2000.asm 8390.asm

ne2000.com: head.obj ne2000.obj tail.obj
	$(LINK) head ne2000 tail,ne2000/m;
	exe2com ne2000
	del ne2000.exe

pm2000.obj: pm2000.asm 8390.asm

pm2000.com: head.obj pm2000.obj tail.obj
	$(LINK) head pm2000 tail,pm2000/m;
	exe2com pm2000
	del pm2000.exe


ne2100.obj: ne2100.asm lance.asm

ne2100.com: head.obj ne2100.obj tail.obj
	$(LINK) head ne2100 tail,ne2100/m;
	exe2com ne2100
	del ne2100.exe

ne2.com: head.obj ne2.obj tail.obj
	$(LINK) head ne2 tail,ne2/m;
	exe2com ne2
	del ne2.exe

ethiie.obj: ethiie.asm 8390.asm

ethiie.com: head.obj ethiie.obj tail.obj
	$(LINK) head ethiie tail,ethiie/m;
	exe2com ethiie
	del ethiie.exe

arcnet.com: head.obj arcnet.obj tail.obj
	$(LINK) head arcnet tail,arcnet/m;
	exe2com arcnet
	del arcnet.exe

arcether.com: head.obj arcether.obj tail.obj
	$(LINK) head arcether tail,arcether/m;
	exe2com arcether
	del arcether.exe

pi.com: head.obj pi.obj tail.obj
	$(LINK) head pi tail,pi/m;
	exe2com pi
	del pi.exe

skeleton.com: head.obj skeleton.obj tail.obj
	$(LINK) head skeleton tail,skeleton/m;
	exe2com skeleton
	del skeleton.exe

nb.com: head.obj nb.obj tail.obj
	$(LINK) head nb tail,nb/m;
	exe2com nb
	del nb.exe

ipxpkt.com: head.obj ipxpkt.obj tail.obj
	$(LINK) head ipxpkt tail,ipxpkt/m;
	exe2com ipxpkt
	del ipxpkt.exe

aquila.com: head.obj aquila.obj tail.obj
	$(LINK) head aquila tail,aquila/m;
	exe2com aquila
	del aquila.exe

tcenet.com: head.obj tcenet.obj tail.obj
	$(LINK) head tcenet tail,tcenet/m;
	exe2com tcenet
	del tcenet.exe

ecoupler.com: head.obj ecoupler.obj tail.obj
	$(LINK) head ecoupler tail,ecoupler/m;
	exe2com ecoupler
	del ecoupler.exe

mylex.com: head.obj mylex.obj tail.obj
	$(LINK) head mylex tail,mylex/m;
	exe2com mylex
	del mylex.exe

tiara.com: head.obj tiara.obj tail.obj
	$(LINK) head tiara tail,tiara/m;
	exe2com tiara
	del tiara.exe

de600.com: head.obj tail.obj de600.obj
        $(LINK) head de600 tail,de600/m;
	exe2com de600
	del de600.exe

davidsys.com: head.obj tail.obj davidsys.obj
        $(LINK) head davidsys tail,davidsys/m;
	exe2com davidsys
	del davidsys.exe

exos205.obj: exos205.asm 82586.asm

exos205.com: head.obj exos205.obj tail.obj
	$(LINK) head exos205 tail,exos205/m;
	exe2com exos205
	del exos205.exe

dk86965.obj: dk86965.asm ecoupler.asm

dk86965.com: head.obj dk86965.obj tail.obj
	$(LINK) head dk86965 tail,dk86965/m;
	exe2com dk86965
	del dk86965.exe

dk86960.com: head.obj dk86960.obj tail.obj
	$(LINK) head dk86960 tail,dk86960/m;
	exe2com dk86960
	del dk86960.exe

versions: nul
	grep -o "version.equ" *.asm

clean: nul
	del *.obj
	del *.com
	del *.exe
	del *.map
